name: Build Chiri CE Firmware
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build Firmware
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          qmk compile -kb keebio/chiri_ce/rev1 -km vial
          echo "=== ГДЕ МОЙ ФАЙЛ? ==="
          find . -maxdepth 2 -type f \( -name "*.uf2" -o -name "*.hex" -o -name "*.bin" \)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chiri_ce_rev1_vial_firmware
          path: |
            *.uf2
            *.hex
            *.bin
            .build/*.uf2
            .build/*.hex
            .build/*.bin
